
networks:
  prefect:
    name: prefect

services:
  # --------------------------------------#
  #               Postgres                #
  # --------------------------------------#
  postgres:
    image: ${POSTGRES_IMAGE}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pg_data
      POSTGRES_HOST_AUTH_METHOD: trust
    healthcheck:
      interval: 10s
      retries: 60
      start_period: 2s
      test: pg_isready -q -d $${POSTGRES_DB} -U $${POSTGRES_USER} | grep "accepting connections" || exit 1
      timeout: 2s
    volumes:
      - ${PWD}/volumes/postgres:/var/lib/postgresql/data/pg_data
    networks:
      - prefect
  # --------------------------------------#
  #             Prefect Server            #
  # --------------------------------------#
  prefect-server:
    container_name: prefect-server
    image: ${PREFECT_IMAGE}
    command: >
      bash -c "prefect server start"
    ports:
      - 4200:4200
    depends_on:
      postgres:
        condition: service_started
    volumes:
      - ${PWD}/volumes/prefect:/root/.prefect
      - ./data:${PREFECT_DATA_PATH}
    environment:
      PREFECT_SERVER_API_HOST: 0.0.0.0
      PREFECT_API_DATABASE_CONNECTION_URL: postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${PREFECT_DATABASE}
      PREFECT_SERVER_ANALYTICS_ENABLED: "false"
      PREFECT_LOGGING_SERVER_LEVEL: WARNING
      PREFECT_API_URL: http://${HOST_OR_IP}:4200/api
    networks:
      - prefect
  # --------------------------------------#
  #             Prefect Worker            #
  # --------------------------------------#
  prefect-worker:
    container_name: prefect-worker
    image: ${PREFECT_IMAGE}
    command:
      - prefect
      - worker
      - start
      - --pool
      - ${PREFECT_WORKER_POOL}
    depends_on:
      prefect-server:
        condition: service_started
    environment:
      PREFECT_API_URL: http://${HOST_OR_IP}:4200/api
      PREFECT_LOGGING_LEVEL: INFO
      PYTHONPATH: ${PREFECT_DATA_PATH}/flows
    volumes:
      - ./data:${PREFECT_DATA_PATH}
    networks:
      - prefect
